### ISSUE TITLE
Accessing properties of a constructor function

### ISSUE THREAD

**Issue by 90zGeneral** [90zGeneral/WDI-Project-1#1]
I'm trying to access some values stores in a constructor but I'm having a hard time with it.

**Comment by 90zGeneral** [comment]
@pavankat 

constructor function and accessing its properties in another function outside of the constructor

var Cell = function (positionRow, positionCol) {  //Create constructor with 2 parameters to re-use later with other objects
    this.posHorizontal = positionRow;            //Set properties to the parameters
    this.posVertical = positionCol;
    this.empty = 'empty';                        //Set a value to an empty postion because the game hasn't begun yet

```
this.isEmpty = function() {                  //Create a function associated to the current value and return a boolean value of true
    return this.empty = 'empty';
},
this.makeRed = function() {                  //Create a function that sets this.value to Red for when game is being played
    return this.empty = 'Red';
}

this.makeBlue = function() {                //Create a function that sets this.value to Blue for the other player 
    return this.empty = 'Blue';
}
```

}

var Cell = function (positionRow, positionCol) {  //Create constructor with 2 parameters to re-use later with other objects
    this.posHorizontal = positionRow;            //Set properties to the parameters
    this.posVertical = positionCol;
    this.empty = 'empty';                        //Set a value to an empty postion because the game hasn't begun yet

```
this.isEmpty = function() {                  //Create a function associated to the current value and return a boolean value of true
    return this.empty = 'empty';
},
this.makeRed = function() {                  //Create a function that sets this.value to Red for when game is being played
    return this.empty = 'Red';
}

this.makeBlue = function() {                //Create a function that sets this.value to Blue for the other player 
    return this.empty = 'Blue';
}
```

}

**Comment by pavankat** [comment]
var Dog = function(n, a){
    this.name = n;
    this.age = a;
}

var fido = new Dog('fido', 3);

fido.name
//outputs to fido

fido.age
outputs to 3

**Comment by pavankat** [comment]
hey Roydon,

if you make a constructor, the purpose is to use it to make many objects.

so in the above example I had a dog constructor, and made an object called fido with it. I accessed the properties fo fido as such: fido.age
