### ISSUE TITLE
column 7 won't click.

### ISSUE THREAD

**Issue by 90zGeneral** [90zGeneral/WDI-Project-1#2]
@DBrodsky90 @pavankat 

var clicked6 = function() {
    var clickedPositionArray = $(this).attr("class").split(" ");
    for(var i = 0; i < operation.table.length; i++) {
        var tableRow = operation.table[i];
        for(var j = 0; j < tableRow.length; j++) {  
            if(tableRow[j].posHorizontal === clickedPositionArray[0] && tableRow[j].posVertical === clickedPositionArray[1]) {
                myObject = tableRow[j];
            }
        }
    }
    console.log(myObject);  
}

The last column will not click and populate in the console like the other columns are. The operation.table.Iength equals to 6 and since there are 7 columns, the loop does not include the last one. tried several different things and nothing works. The divs with a class 'row' each has 7 columns inside of them so I tried replacing tableRow with '.row'.length and that does not work either.

**Comment by 90zGeneral** [comment]
@WilliamfShaw

**Comment by pavankat** [comment]
hey Roydon the last column isn't being called via a click event. The click event might not even be there for it

or the code running in the click event on the last column is not working properly. If that's the case then

throw a debugger above at the top of the click event, and see if it stops there when you click the last column and debug from there.
