### ISSUE TITLE
Populating a color for each cell

### ISSUE THREAD

**Issue by 90zGeneral** [90zGeneral/WDI-Project-1#3]
@pavankat @DBrodsky90 @WilliamfShaw @awongh 

var line1 = $('#col0');                        //Grab every cell in col 0.
var line2 = $('#col1');                        //Grab every cell in col 1.
var line3 = $('#col2');
var line4 = $('#col3');
var line5 = $('#col4');
var line6 = $('#col5');

var turn = 0;

var clicked = function() { 
    var clickedPositionArray = $(this).attr("class").split(" ");
    console.log(clickedPositionArray)
    for(var i = 0; i < operation.table.length; i++) {
        var tableRow = operation.table[i];
        for(var j = 0; j < tableRow.length; j++) {  
            if(tableRow[j].posHorizontal === clickedPositionArray[1] && tableRow[j].posVertical === clickedPositionArray[2]) {
                myObject = tableRow[j];
            }
        }
    }
    //check to see what the nearest empty one is
    console.log(myObject)
    var vert = "." + myObject.posVertical
    var column = $(vert);
    var index = vert[vert.length - 1]
    console.log(index)

```
for(var k = 0; k < operation.table.length; k++){
    var currentRow = operation.table[k]
    for(var l = 0; l < currentRow.length; l++){
        if(currentRow[index].isEmpty()) {
            $(".row" + k + ".col" + index).css("background-color", "red");
        }
    }
}
```

};

Can I get some help. I cannot get the cells to change color when its clicked. I tried accessing each cell separately but that doesn't work either. I guessing that the .split() method is preventing it from changing color because I'm not sure if you can apply css to an array. I also pushed up my most recent code with all the files to github.

**Comment by pavankat** [comment]
I got this

**Comment by pavankat** [comment]
@90zGeneral I cloned your repo and opened up the console

I got this: Uncaught ReferenceError: myObject is not defined in click.js

you just never defined that variable anywhere. 

When you get that working, then throw in a debugger; into the clicked function. Click on something, and try things there in the console until you can get what you want happening.

**Comment by 90zGeneral** [comment]
it's a global variable inside the function

**Comment by 90zGeneral** [comment]
@pavankat

**Comment by DBrodsky90** [comment]
Roydon, I cloned your repo and I am also getting myObject is undefined. You are trying to set myObject on line 17 in click.js but its never getting there cause the conditions aren't met. And they are not being met because another class of "cols" was added and it is messing up clickedPositionArray. In your code you have a console.log(clickedPositionArray);. Have you even looked at console and see what it was giving you and how it might affect your code?

**Comment by 90zGeneral** [comment]
Yea I did. Remember when you were working on it with me and you said that myObject is global inside the function. Everything was ok at that point. Will added another nested for loop similar to the one you helped me with and that made the entire column change to red. I didnt change anything you guys did except the fact that I need only the bottom cell to change color when clicked so i tried doing a few things but each time it didnt work, I put it back to the way you guys had it. If i make myObject local inside the function then it messing up posVertical.

**Comment by DBrodsky90** [comment]
The last time I seen it was when you clicked on it and it make the whole column red. That was a pretty big move forward. Now myObect is undefined. I suggest going back to when it made the whole column red and try and figure out how to only make the bottom one red.

**Comment by 90zGeneral** [comment]
That's what I'm trying to do. Everytime I try something and it don't work, I put it back to the way you guys had it so I don't know why it's giving me an error now. myObject is the same from when u did it so why is it causing problems now? That what I can't understand.

**Comment by pavankat** [comment]
Roydon, it's giving you issues because the conditions aren't being met

var count = 4;

if (count < 3){
   thing = 'hi'
}

console.log(thing)
//this will break

---

var count = 4;
var thing;

if (count < 3){
   thing = 'hi'
}

console.log(thing)
//this will not break
