### ISSUE TITLE
winning combos

### ISSUE THREAD

**Issue by 90zGeneral** [90zGeneral/WDI-Project-1#4]
@pavankat @WilliamfShaw @DBrodsky90 

Good Afternoon,
I cannot get the game to alert nor console.log a winning combo. I created a nested array with all 69 winning combos and loop through them. I've tried using debugger but not sure if i'm doing it correctly and i'm not getting any errors in the console, which is not a good sign. Can someone take a look and see what's wrong. The files have been pushed up to github. Thanks

**Comment by awongh** [comment]
Hi, you didn't tag me, but I'm going to comment anyways :-)

Can you please describe exactly what is not working? -You said that you are using a loop- what does the loop do or not do that does or does not cause the expected behavior? Do you have an idea of where in the code the loop does or does not work? 

In loops you can either use a `debugger;` line inside the loop, or you can do a `console.log()` inside the loop to print values that you are expecting. 

Can you please link to the file and line number that you want us to look at? (example: https://github.com/90zGeneral/WDI-Project-1/blob/master/game.js#L2)

Can you please give exact step-by-step instructions on how to reproduce the problem you are seeing? Please be as detailed as possible.

**Comment by 90zGeneral** [comment]
@awongh 

sorry, I didn't realize that i left u out smh. I did put some console.log within the loop but nothing works.

Ok, I created a variable that holds the unique name of each cell on the board, then I stored those variable names in an array with all the winning combos. Then i made a nested for loop to check for the matches and produce a winner. I used console.log and alert to let me know if the program is running but I'm not getting anything.

https://github.com/90zGeneral/WDI-Project-1/blob/master/winnings.js

**Comment by awongh** [comment]
Can you please be more specific about "not getting anything"?

Does that mean that the `console.log` doesn't print out anything? Or is it simply not executed?

**Comment by 90zGeneral** [comment]
I think it's both. Nothing is being printed to the console and i'm guessing its because the execution is not working.

**Comment by awongh** [comment]
For this block of code:

```
var whoWon = function () {
    for(var i = 0; i < winningCombos.length; i++) {
        for(var j = 0; j < winningCombos[i].length; j++) {
            var redCount = 0,
            blueCount = 0;
            for (var k = 0; k < winningCombos[i][j].length; k++) {
                if (winningCombos[i][j][k].attr('class') === 'player1') {
                    redCount++;
                    if(redCount === 4) {
                        alert("player1 won");
                    }
                    console.log('player1 ' + blueCount);
                }
                else if (winningCombos[i][j][k].attr('class') === 'player2') {
                    blueCount++;
                    if (blueCount === 4) {
                        alert("player2 won");
                    }
                    console.log('player2 ' + redCount);
                }
            }
        }   
    }

};
```

Please add some comments so that by reading it I can understand what each line of each part of the loop does:
(example:)

```
var whoWon = function () {
        //look in every single winning combo
    for(var i = 0; i < winningCombos.length; i++) {
                //look in a single winning combo
        for(var j = 0; j < winningCombos[i].length; j++) {
                        //initialize a count for red piece count
            var redCount = 0,
            blueCount = 0;
            for (var k = 0; k < winningCombos[i][j].length; k++) {
                if (winningCombos[i][j][k].attr('class') === 'player1') {
                    redCount++;
                    if(redCount === 4) {
                        alert("player1 won");
                    }
                    console.log('player1 ' + blueCount);
                }
                else if (winningCombos[i][j][k].attr('class') === 'player2') {
                    blueCount++;
                    if (blueCount === 4) {
                        alert("player2 won");
                    }
                    console.log('player2 ' + redCount);
                }
            }
        }   
    }

};

```

another thing that should be helpful is to rename your variables inside your loop, or initialize variables that can make reading the code easier:

```
  var alphabet = ['a','b','c','d','e','f','g'];
  for( var letterIndex =0; letterIndex < alphabet.length; letterIndex++ ){
    var currentLetter = alphabet[letterIndex];

    // etc, now you have a currentLetter to work with instead of alphabet[i]
    // reading or trying to think about what alphabet[i][j][k] can be confusing 
    // and hard to tell what the current value is
    // 
  }
```

**Comment by 90zGeneral** [comment]
Yeah I was gonna add the comments later because I wanted to make sure that its working first before adding comments to avoid deleting them if it doesn't work. I don't think that the variables are the problem but I will try your advice and see what happens.

**Comment by awongh** [comment]
comments aren't something that you add later, in fact most times I start with comments before writing any lines of actual code- they tell you and anyone reading your code what your code is doing- _SO_ if you can't write comments about what your code is doing before you write the code it might mean you don't know what your code is doing ;-)

_DONT BE AFRAID TO BREAK THINGS_
Don't be afraid of writing things that don't work or might break or are inaccurate- you can always delete them later. 

the variables are probably not the "problem" but rewriting it more explicitly can expose the actual problem- all programmers regardless of experience have trouble with understanding the current context of a value in nested loops. (https://en.wikipedia.org/wiki/Off-by-one_error)

But naming things well can make your code clearer to yourself and anyone else reading it that is trying to find the problem.
